### ISSUE TITLE
Thew view does not exist

### ISSUE THREAD

**Issue by jimhill21** [gilek/yii2-gtreetable#10]
I followed the install instructions very carefully but I get the following error...

The view file does not exist: /var/www/application/_protected/frontend/views/site/gilek/gtreetable/views/widget.php

I installed using composer and it's in the vendors directiory.  I verified the psr-4 is set as well.

**Comment by gilek** [comment]
Try to change view location on @gilek/gtreetable/views/widget

**Comment by jimhill21** [comment]
You're the man!!  Why couldn't I use the view location specified in the docs?
