### ISSUE TITLE
passing an event in actions array to widget causes error

### ISSUE THREAD

**Issue by jimhill21** [gilek/yii2-gtreetable#11]
I'm currently trying to add a custom action to the gtreetable widget.  Whenever I pass anything to the event, I get the following error...   "Uncaught TypeError: string is not a function".

Here's my code sample...

        return $this->render('@gilek/gtreetable/views/widget', ['options' => [
            'manyroots' => true,
            'draggable' => true,
            'inputWidth' => '300px',
            'actions' => array(
                array(
                    'name' => 'Upload Image',
                    'event' => 'js:function(node) {
                        alert("OK");
                    }'
                ),
            )
        ]]);

**Comment by gilek** [comment]
Change:
 
```php
'event' => 'js:function(node) {
    alert("OK");
}' 
```   

to:
``` php
'event' => new \yii\web\JsExpression('function(node) {
    alert("OK");
}')
```
