### ISSUE TITLE
Installing with "minimum-stability": "stable"

### ISSUE THREAD

**Issue by bsploit** [gilek/yii2-gtreetable#12]
Hi!
if in composer.json there is "minimum-stability": "stable" then extension could not be installed.
If I change to "minimum-stability": "dev", then it installs

**Comment by gilek** [comment]
Hi,
it works fine, cause there is no stable version yet.

**Comment by adiramardiani** [comment]
but whether it should be the "minimum-stability": "dev"?
dependency while others use a "minimum-stability": "stable", whether to sacrifice everything and revert to the dev version just for this plugin?

whether to minimum-stability with stable course?

thanks

**Comment by gilek** [comment]
Try this, in the require section, change

`"gilek/yii2-gtreetable": "*"`

to:

`"bower-asset/bootstrap-gtreetable": "2.*@dev",
"gilek/yii2-gtreetable": "1.1.1-alpha@dev"`

**Comment by rulon** [comment]
"bower-asset/bootstrap-gtreetable": "2.*@dev",
        "gilek/yii2-gtreetable": "1.1.1-alpha@dev"
===
directory
'@bower/jquery.browser/dist'
not found
