### ISSUE TITLE
Add custom field in when add nodes

### ISSUE THREAD

**Issue by adiramardiani** [gilek/yii2-gtreetable#14]
Currently the field added is 'name' only, how to add some field again, like (because implement for menu) 'url' field, or other field ?

**Comment by amstr1k** [comment]
@gilek it would be nice to add the ability to add fields. For example, "Published"

**Comment by gilek** [comment]
At this moment there is no possibility to manage inputs in bootstrap-gtreetable JS plugin. I must figure out way to implement it.

**Comment by des1roer** [comment]
very need add some custom field
