### ISSUE TITLE
Error into dependencies

### ISSUE THREAD

**Issue by efureev** [gilek/yii2-gtreetable#18]
![e5c6f0ce61](https://cloud.githubusercontent.com/assets/5524684/10401014/b1aeb0c8-6ed5-11e5-8518-6cdfc2945d30.jpg)

**Comment by luobenyu** [comment]
## Hey there!
### I solved this (and , sort of) problems by updating  ' composer-fxp '  plugins,  ' creocoder/yii2-nested-sets ' , and finally  ' yii2-gtreetable itself ' . 
### Remember to add the very root record ,see 
> https://github.com/gilek/yii2-gtreetable/ .
