### ISSUE TITLE
composer update fails

### ISSUE THREAD

**Issue by sunrom** [gilek/yii2-gtreetable#8]
the composer seeks below as required for yii2-gtreetable
"creocoder/yii2-nested-set-behavior": "*",

but that has been renamed to below now, so composer install/update fails.
https://github.com/creocoder/yii2-nested-sets

**Comment by sunrom** [comment]
Also following line needs to be updated in composer.json
OLD: "bower-asset/bootstrap-gtreetable" : "2.*",
NEW: "bower-asset/bootstrap-gtreetable" : "2.*@dev",

**Comment by sunrom** [comment]
i added following line to install
     "gilek/yii2-gtreetable": "dev-master"

it fails with attached error.
![untitled-1](https://cloud.githubusercontent.com/assets/1452967/5762926/e7b2d8ee-9d0b-11e4-9304-1d83bb0a7e26.gif)

**Comment by gilek** [comment]
Now it should work.
